### Fonts
font_size 14.0
cursor_trail 1

### Window
window_padding_width 12
background_opacity 0.8

### Color Scheme
background #0a0a0a

# yellow
color3  #f4bf75
color11 #fffd00

# blue
color4  #6a9fb5
color12 #1a8fff

# magenta
color5  #aa759f
color13 #fd28ff

# white
color7  #d8d8d8
color15 #ffffff
